using System;
using System.Text;
using nHydrate.Generator.Common.Forms;
using nHydrate.Generator.Models;

namespace nHydrate.Generator
{
	public static class GenerationHelper
	{
		public static void AppendCopyrightInCode(StringBuilder sb, ModelRoot model)
		{
			if (!string.IsNullOrEmpty(model.Copyright))
			{
				sb.AppendLine("#region Copyright (c) " + DateTime.Now.Year + " " + model.CompanyName + ", All Rights Reserved");

				var temp = model.Copyright.Replace("\r\n", "\n");
				temp = temp.Replace("\r", "\n");
				temp = temp.Replace("%year%", DateTime.Now.Year.ToString());
				var arr = temp.Split('\n');
				foreach (var s in arr)
				{
					sb.AppendLine("//" + s);
				}
				sb.AppendLine("#endregion");
				sb.AppendLine();
			}
		}

		public static void AppendCopyrightInSQL(StringBuilder sb, ModelRoot model)
		{
			if (!string.IsNullOrEmpty(model.Copyright))
			{
				sb.AppendLine("--Copyright (c) " + DateTime.Now.Year + " " + model.CompanyName + ", All Rights Reserved");

				var temp = model.Copyright.Replace("\r\n", "\n");
				temp = temp.Replace("\r", "\n");
				temp = temp.Replace("%year%", DateTime.Now.Year.ToString());
				var arr = temp.Split('\n');
				foreach (var s in arr)
				{
					sb.AppendLine("--" + s);
				}
				sb.AppendLine();
			}
		}

		public static void AppendFileGeneatedMessageInCode(StringBuilder sb)
		{
			sb.AppendLine("//------------------------------------------------------------------------------");
			sb.AppendLine("// <auto-generated>");
			sb.AppendLine("//    This code was generated from a template.");
			sb.AppendLine("//");
			sb.AppendLine("//    Manual changes to this file may cause unexpected behavior in your application.");
			sb.AppendLine("//    Manual changes to this file will be overwritten if the code is regenerated.");
			sb.AppendLine("// </auto-generated>");
			sb.AppendLine("//------------------------------------------------------------------------------");
			sb.AppendLine();
		}

		public static void ShowError(string text)
		{
			var F = new ErrorForm(text, "No other information is available.");
			F.ShowDialog();
		}

		public static void ShowError(string text, Exception exception)
		{
			var F = new ErrorForm(text, exception.ToString());
			F.ShowDialog();
		}


	}
}

