#pragma warning disable IDE1006 // Naming Styles
// All of these classes were generated by using the "Paste Special" functionality with the XML in the nHydrate model files folder

using System.Xml.Serialization;

namespace nHydrate.ModelManagement.Entity
{

    // NOTE: Generated code may require at least .NET Framework 4.5 or .NET Core/Standard 2.0.
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class configuration
    {

        private string summaryField;

        private configurationField[] fieldsetField;

        private string typeField;

        private string nameField;

        private string idField;

        private byte allowcreateauditField;

        private byte allowmodifyauditField;

        private byte allowtimestampField;

        private string codefacadeField;

        private byte immutableField;

        private byte isassociativeField;

        private string typedentityField;

        private string schemaField;

        private byte generatesdoublederivedField;

        private byte isTenantField;

        /// <remarks/>
        public string summary
        {
            get
            {
                return this.summaryField;
            }
            set
            {
                this.summaryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("field", IsNullable = false)]
        public configurationField[] fieldset
        {
            get
            {
                return this.fieldsetField;
            }
            set
            {
                this.fieldsetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte allowcreateaudit
        {
            get
            {
                return this.allowcreateauditField;
            }
            set
            {
                this.allowcreateauditField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte allowmodifyaudit
        {
            get
            {
                return this.allowmodifyauditField;
            }
            set
            {
                this.allowmodifyauditField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte allowtimestamp
        {
            get
            {
                return this.allowtimestampField;
            }
            set
            {
                this.allowtimestampField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string codefacade
        {
            get
            {
                return this.codefacadeField;
            }
            set
            {
                this.codefacadeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte immutable
        {
            get
            {
                return this.immutableField;
            }
            set
            {
                this.immutableField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte isassociative
        {
            get
            {
                return this.isassociativeField;
            }
            set
            {
                this.isassociativeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string typedentity
        {
            get
            {
                return this.typedentityField;
            }
            set
            {
                this.typedentityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string schema
        {
            get
            {
                return this.schemaField;
            }
            set
            {
                this.schemaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte generatesdoublederived
        {
            get
            {
                return this.generatesdoublederivedField;
            }
            set
            {
                this.generatesdoublederivedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte isTenant
        {
            get
            {
                return this.isTenantField;
            }
            set
            {
                this.isTenantField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class configurationField
    {

        private string summaryField;

        private string idField;

        private string nameField;

        private byte nullableField;

        private string datatypeField;

        private string identityField;

        private string codefacadeField;

        private string dataformatstringField;

        private string defaultField;

        private byte defaultisfuncField;

        private string formulaField;

        private byte isindexedField;

        private byte isprimarykeyField;

        private byte iscalculatedField;

        private byte isuniqueField;

        private int lengthField;

        private byte scaleField;

        private byte sortorderField;

        private byte isreadonlyField;

        private byte obsoleteField;

        /// <remarks/>
        public string summary
        {
            get
            {
                return this.summaryField;
            }
            set
            {
                this.summaryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte nullable
        {
            get
            {
                return this.nullableField;
            }
            set
            {
                this.nullableField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string datatype
        {
            get
            {
                return this.datatypeField;
            }
            set
            {
                this.datatypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string identity
        {
            get
            {
                return this.identityField;
            }
            set
            {
                this.identityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string codefacade
        {
            get
            {
                return this.codefacadeField;
            }
            set
            {
                this.codefacadeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dataformatstring
        {
            get
            {
                return this.dataformatstringField;
            }
            set
            {
                this.dataformatstringField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @default
        {
            get
            {
                return this.defaultField;
            }
            set
            {
                this.defaultField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte defaultisfunc
        {
            get
            {
                return this.defaultisfuncField;
            }
            set
            {
                this.defaultisfuncField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string formula
        {
            get
            {
                return this.formulaField;
            }
            set
            {
                this.formulaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte isindexed
        {
            get
            {
                return this.isindexedField;
            }
            set
            {
                this.isindexedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte isprimarykey
        {
            get
            {
                return this.isprimarykeyField;
            }
            set
            {
                this.isprimarykeyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte Iscalculated
        {
            get
            {
                return this.iscalculatedField;
            }
            set
            {
                this.iscalculatedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte isunique
        {
            get
            {
                return this.isuniqueField;
            }
            set
            {
                this.isuniqueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int length
        {
            get
            {
                return this.lengthField;
            }
            set
            {
                this.lengthField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte scale
        {
            get
            {
                return this.scaleField;
            }
            set
            {
                this.scaleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte sortorder
        {
            get
            {
                return this.sortorderField;
            }
            set
            {
                this.sortorderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte isreadonly
        {
            get
            {
                return this.isreadonlyField;
            }
            set
            {
                this.isreadonlyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte obsolete
        {
            get
            {
                return this.obsoleteField;
            }
            set
            {
                this.obsoleteField = value;
            }
        }
    }


}

namespace nHydrate.ModelManagement.Index
{


    // NOTE: Generated code may require at least .NET Framework 4.5 or .NET Core/Standard 2.0.
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class configuration
    {

        private configurationIndex[] indexField;

        private string typeField;

        private string idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("index")]
        public configurationIndex[] index
        {
            get
            {
                return this.indexField;
            }
            set
            {
                this.indexField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class configurationIndex
    {

        private string summaryField;

        private configurationIndexColumn[] indexcolumnsetField;

        private string idField;

        private byte clusteredField;

        private string importednameField;

        private byte indextypeField;

        private byte isuniqueField;

        /// <remarks/>
        public string summary
        {
            get
            {
                return this.summaryField;
            }
            set
            {
                this.summaryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("column", IsNullable = false)]
        public configurationIndexColumn[] indexcolumnset
        {
            get
            {
                return this.indexcolumnsetField;
            }
            set
            {
                this.indexcolumnsetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte clustered
        {
            get
            {
                return this.clusteredField;
            }
            set
            {
                this.clusteredField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string importedname
        {
            get
            {
                return this.importednameField;
            }
            set
            {
                this.importednameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte indextype
        {
            get
            {
                return this.indextypeField;
            }
            set
            {
                this.indextypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte isunique
        {
            get
            {
                return this.isuniqueField;
            }
            set
            {
                this.isuniqueField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class configurationIndexColumn
    {

        private string idField;

        private byte ascendingField;

        private string fieldidField;

        private int sortorderField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte ascending
        {
            get
            {
                return this.ascendingField;
            }
            set
            {
                this.ascendingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string fieldid
        {
            get
            {
                return this.fieldidField;
            }
            set
            {
                this.fieldidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int sortorder
        {
            get
            {
                return this.sortorderField;
            }
            set
            {
                this.sortorderField = value;
            }
        }
    }


}

namespace nHydrate.ModelManagement.Relation
{

    // NOTE: Generated code may require at least .NET Framework 4.5 or .NET Core/Standard 2.0.
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class configuration
    {

        private configurationRelation[] relationField;

        private string typeField;

        private string idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("relation")]
        public configurationRelation[] relation
        {
            get
            {
                return this.relationField;
            }
            set
            {
                this.relationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class configurationRelation
    {

        private string summaryField;

        private configurationRelationField[] relationfieldsetField;

        private string idField;

        private string childidField;

        private byte isenforcedField;

        private string deleteactionField;

        private string rolenameField;

        /// <remarks/>
        public string summary
        {
            get
            {
                return this.summaryField;
            }
            set
            {
                this.summaryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("field", IsNullable = false)]
        public configurationRelationField[] relationfieldset
        {
            get
            {
                return this.relationfieldsetField;
            }
            set
            {
                this.relationfieldsetField = value;
            }
        }

        /// <summary>
        /// Internal ID
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string childid
        {
            get
            {
                return this.childidField;
            }
            set
            {
                this.childidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte isenforced
        {
            get
            {
                return this.isenforcedField;
            }
            set
            {
                this.isenforcedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string deleteaction
        {
            get
            {
                return this.deleteactionField;
            }
            set
            {
                this.deleteactionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rolename
        {
            get
            {
                return this.rolenameField;
            }
            set
            {
                this.rolenameField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class configurationRelationField
    {

        private string idField;

        private string sourcefieldidField;

        private string targetfieldidField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sourcefieldid
        {
            get
            {
                return this.sourcefieldidField;
            }
            set
            {
                this.sourcefieldidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string targetfieldid
        {
            get
            {
                return this.targetfieldidField;
            }
            set
            {
                this.targetfieldidField = value;
            }
        }
    }


}

namespace nHydrate.ModelManagement.StaticData
{

    // NOTE: Generated code may require at least .NET Framework 4.5 or .NET Core/Standard 2.0.
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class configuration
    {

        private configurationData[] dataField;

        private string typeField;

        private string idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data")]
        public configurationData[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class configurationData
    {

        private string columnkeyField;

        private string valueField;

        private int orderkeyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string columnkey
        {
            get
            {
                return this.columnkeyField;
            }
            set
            {
                this.columnkeyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int orderkey
        {
            get
            {
                return this.orderkeyField;
            }
            set
            {
                this.orderkeyField = value;
            }
        }
    }


}

namespace nHydrate.ModelManagement.View
{

    // NOTE: Generated code may require at least .NET Framework 4.5 or .NET Core/Standard 2.0.
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class configuration
    {

        private string summaryField;

        private configurationField[] fieldsetField;

        private string typeField;

        private string nameField;

        private string idField;

        private string codefacadeField;

        private string schemaField;

        private byte generatesdoublederivedField;

        /// <remarks/>
        public string summary
        {
            get
            {
                return this.summaryField;
            }
            set
            {
                this.summaryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("field", IsNullable = false)]
        public configurationField[] fieldset
        {
            get
            {
                return this.fieldsetField;
            }
            set
            {
                this.fieldsetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string codefacade
        {
            get
            {
                return this.codefacadeField;
            }
            set
            {
                this.codefacadeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string schema
        {
            get
            {
                return this.schemaField;
            }
            set
            {
                this.schemaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte generatesdoublederived
        {
            get
            {
                return this.generatesdoublederivedField;
            }
            set
            {
                this.generatesdoublederivedField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class configurationField
    {

        private string summaryField;

        private string idField;

        private string nameField;

        private byte nullableField;

        private string datatypeField;

        private string codefacadeField;

        private string defaultField;

        private int lengthField;

        private byte scaleField;

        private byte isprimarykeyField;

        /// <remarks/>
        public string summary
        {
            get
            {
                return this.summaryField;
            }
            set
            {
                this.summaryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte nullable
        {
            get
            {
                return this.nullableField;
            }
            set
            {
                this.nullableField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string datatype
        {
            get
            {
                return this.datatypeField;
            }
            set
            {
                this.datatypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string codefacade
        {
            get
            {
                return this.codefacadeField;
            }
            set
            {
                this.codefacadeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @default
        {
            get
            {
                return this.defaultField;
            }
            set
            {
                this.defaultField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int length
        {
            get
            {
                return this.lengthField;
            }
            set
            {
                this.lengthField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte scale
        {
            get
            {
                return this.scaleField;
            }
            set
            {
                this.scaleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte isprimarykey
        {
            get
            {
                return this.isprimarykeyField;
            }
            set
            {
                this.isprimarykeyField = value;
            }
        }
    }


}

namespace nHydrate.ModelManagement.Entity
{
    partial class configuration
    {
        public override string ToString() => this.name;
    }

    partial class configurationField
    {
        public override string ToString() => this.name;
    }
}

namespace nHydrate.ModelManagement.Relation
{
    partial class configuration
    {
        public override string ToString() => this.id;
    }
}

namespace nHydrate.ModelManagement.View
{
    partial class configuration
    {
        [XmlIgnore]
        public string sql { get; set; }

        public override string ToString() => this.name;
    }
}
