//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq;

namespace Acme.Northwind.EFDAL.Interfaces.Entity
{
	/// <summary>
	/// This is the interface for the entity CustomerandSuppliersbyCity
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("nHydrateModelGenerator", "5.1.2")]
	public partial interface ICustomerandSuppliersbyCity
	{
		#region Properties

		/// <summary>
		/// The property for the field 'City'
		/// </summary>
		string City { get; }

		/// <summary>
		/// The property for the field 'CompanyName'
		/// </summary>
		string CompanyName { get; }

		/// <summary>
		/// The property for the field 'ContactName'
		/// </summary>
		string ContactName { get; }

		/// <summary>
		/// The property for the field 'Relationship'
		/// </summary>
		string Relationship { get; }

		#endregion

	}

}

