//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq;

namespace Acme.Northwind.EFDAL.Interfaces.Entity
{
	/// <summary>
	/// This is the interface for the entity OrdersQry
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("nHydrateModelGenerator", "5.1.2")]
	public partial interface IOrdersQry
	{
		#region Properties

		/// <summary>
		/// The property for the field 'Address'
		/// </summary>
		string Address { get; }

		/// <summary>
		/// The property for the field 'City'
		/// </summary>
		string City { get; }

		/// <summary>
		/// The property for the field 'CompanyName'
		/// </summary>
		string CompanyName { get; }

		/// <summary>
		/// The property for the field 'Country'
		/// </summary>
		string Country { get; }

		/// <summary>
		/// The property for the field 'CustomerID'
		/// </summary>
		string CustomerID { get; }

		/// <summary>
		/// The property for the field 'EmployeeID'
		/// </summary>
		int? EmployeeID { get; }

		/// <summary>
		/// The property for the field 'Freight'
		/// </summary>
		decimal? Freight { get; }

		/// <summary>
		/// The property for the field 'OrderDate'
		/// </summary>
		DateTime? OrderDate { get; }

		/// <summary>
		/// The property for the field 'OrderID'
		/// </summary>
		int OrderID { get; }

		/// <summary>
		/// The property for the field 'PostalCode'
		/// </summary>
		string PostalCode { get; }

		/// <summary>
		/// The property for the field 'Region'
		/// </summary>
		string Region { get; }

		/// <summary>
		/// The property for the field 'RequiredDate'
		/// </summary>
		DateTime? RequiredDate { get; }

		/// <summary>
		/// The property for the field 'ShipAddress'
		/// </summary>
		string ShipAddress { get; }

		/// <summary>
		/// The property for the field 'ShipCity'
		/// </summary>
		string ShipCity { get; }

		/// <summary>
		/// The property for the field 'ShipCountry'
		/// </summary>
		string ShipCountry { get; }

		/// <summary>
		/// The property for the field 'ShipName'
		/// </summary>
		string ShipName { get; }

		/// <summary>
		/// The property for the field 'ShippedDate'
		/// </summary>
		DateTime? ShippedDate { get; }

		/// <summary>
		/// The property for the field 'ShipPostalCode'
		/// </summary>
		string ShipPostalCode { get; }

		/// <summary>
		/// The property for the field 'ShipRegion'
		/// </summary>
		string ShipRegion { get; }

		/// <summary>
		/// The property for the field 'ShipVia'
		/// </summary>
		int? ShipVia { get; }

		#endregion

	}

}

