//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq;

namespace Acme.Northwind.EFDAL.Interfaces.Entity
{
	/// <summary>
	/// This is the interface for the entity SalesbyCategory
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("nHydrateModelGenerator", "5.1.2")]
	public partial interface ISalesbyCategory
	{
		#region Properties

		/// <summary>
		/// The property for the field 'CategoryID'
		/// </summary>
		int CategoryID { get; }

		/// <summary>
		/// The property for the field 'CategoryName'
		/// </summary>
		string CategoryName { get; }

		/// <summary>
		/// The property for the field 'ProductName'
		/// </summary>
		string ProductName { get; }

		/// <summary>
		/// The property for the field 'ProductSales'
		/// </summary>
		decimal? ProductSales { get; }

		#endregion

	}

}

